spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    charset: utf-8
    content-type: text/html;charset=UTF-8
    request-context-attribute: "rc"
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    allow-request-override: false
    allow-session-override: false
    prefer-file-system-access: true
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB