spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mysql_learn?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update #ddl-auto:设为update 表示每次都重新建表
        show-sql: true

#swagger api文档生成
swagger:
    enabled: true